[project]
authors = ["Katy Scott <k.l.scott16@gmail.com>", "Katarina Vucic <katarina.vucic03@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "data_querying"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
notebook_kernel = "ipython kernel install --name=image_query --display-name=image_query --user"

[dependencies]
python = ">=3.13.2,<3.14"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
